<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">

	<xsl:template match="/">
		<xsl:apply-templates select="fiches"/>
	</xsl:template>

	<xsl:template match="fiches">
		<document pageSize="21cm,29.7cm" leftMargin="1.0cm" rightMargin="6.0cm" topMargin="0.2cm" bottomMargin="0.8cm" title="Fiches" author="Generated by Tiny ERP, Fabien Pinckaers">
			<template>
				<pageTemplate id="first">
					<pageGraphics>
					</pageGraphics>
					<frame id="first" x1="1.1cm" y1="19.5cm" width="13cm" height="9.3cm"/>
					<frame id="second" x1="1.1cm" y1="10.0cm" width="13cm" height="9.2cm"/>
					<frame id="third" x1="1.1cm" y1="0.6cm" width="13cm" height="9.3cm"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<initialize>
				</initialize>
				<blockTableStyle id="fiches1">
					 <blockValign value="MIDDLE"/>
					 <blockAlignment value="CENTER"/>
					 <blockFont name="Helvetica-BoldOblique" size="14" start="2,0" stop="2,0"/>
					 <blockFont name="Helvetica-BoldOblique" size="14" start="4,0" stop="4,0"/>
				</blockTableStyle>
				<blockTableStyle id="fiches2">
					 <blockValign value="MIDDLE"/>
					 <blockAlignment value="CENTER"/>
				</blockTableStyle>
			</stylesheet>
			<story>
				<xsl:apply-templates select="fiche"/>
			</story>
		</document>
	</xsl:template>

	<xsl:template match="fiche">
		<blockTable rowHeights="1.1cm" colWidths="1.1cm,2.5cm,3.5cm,2.5cm,3.5cm" style="fiches1">
			<tr>
				<td/>
				<td><xsl:value-of select="lot-inv"/>-<xsl:value-of select="lot-num"/></td>
				<td><xsl:value-of select="obj-num"/></td>
				<td><xsl:value-of select="lot-inv"/>-<xsl:value-of select="lot-num"/></td>
				<td><xsl:value-of select="obj-num"/></td>
			</tr>
		</blockTable>
		<blockTable rowHeights="1.1cm,1.1cm" colWidths="1.1cm,6.0cm,6.0cm" style="fiches2">
			<tr>
				<td/>
				<td><para><xsl:value-of select="lot-obj"/></para></td>
				<td><para><xsl:value-of select="lot-obj"/></para></td>
			</tr><tr>
				<td/>
				<td><xsl:value-of select="vnd-name"/></td>
				<td/>
			</tr>
		</blockTable>
		
		<spacer height="5mm" width="1cm"/>
		
		<para>
			<xsl:value-of select="lot-limit"/> EUR
		</para>
		
		<nextFrame/>
	</xsl:template>
</xsl:stylesheet>
