all: test_simple vcard
	

test_simple:
	./test1.py
	./test2.py
	./test3.py
	./test4.py
	./map.py

test_openobject:
	./test5.py

vcard:
	./test_vcard.py

clean:
	rm -f *pyc
	rm -f output/*
	rm -f intermediate/*
