# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.3
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: null
repo_name: Tools to upgrade Odoo instances from a major version to another
repo_slug: openupgrade
travis_apt_packages: []
travis_apt_sources: []
