# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: null
repo_name: 'Open Source upgrade path for Odoo/OpenERP '
repo_slug: openupgrade
repo_website: https://github.com/OCA/OpenUpgrade
travis_apt_packages: []
travis_apt_sources: []

