#!/bin/sh

OUTPUT_DIR=$(realpath $(dirname $0)/./docs)
SOURCE_DIR=$(realpath $(dirname $0)/./docsource)
ODOO_PYTHON_PATH=$(realpath $(dirname $0)/./odoo)

BASE_URL=https://raw.githubusercontent.com/OCA/OpenUpgrade/
DOC_PARTS="7.0/openerp/openupgrade/doc/source/modules50-60.rst
7.0/openerp/openupgrade/doc/source/modules60-61.rst
7.0/openerp/openupgrade/doc/source/modules61-70.rst
8.0/openerp/openupgrade/doc/source/modules70-80.rst
9.0/openerp/openupgrade/doc/source/modules80-90.rst
10.0/odoo/openupgrade/doc/source/modules90-100.rst
11.0/odoo/openupgrade/doc/source/modules100-110.rst
12.0/odoo/openupgrade/doc/source/modules110-120.rst
13.0/odoo/openupgrade/doc/source/modules120-130.rst
14.0/docsource/modules130-140.rst
15.0/docsource/modules140-150.rst
16.0/docsource/modules150-160.rst
"

for line in $DOC_PARTS; do
    if [ -z "$line" ]; then
        continue
    fi
    name=$(basename $line)
    wget -q $BASE_URL/$line -O $SOURCE_DIR/$name
done

export PYTHONPATH=$PYTHONPATH:$ODOO_PYTHON_PATH

mkdir -p $OUTPUT_DIR/source/.static

python3 -m sphinx -W -q -d $OUTPUT_DIR/.doctrees $SOURCE_DIR $OUTPUT_DIR
