{
    "name":"Ampco",
    "version":"1.0",
    "author":"Tiny",
    "category":"Ampco",
    "depends":[
        "base","product","sale"
       ],
    "demo_xml":[],
    "update_xml":[
            "ampco_view.xml",
            "product_heatcode/product_heatcode_view.xml",
            "product_lot_foundary/product_lot_foundary.xml",
          ],
    "installable":True,
}
