{'category': 'Data Module', 
'init_xml': ['auction_db.xml',
			'auction.lot.category.csv',
			'account.tax.csv',
			'res.partner.csv', 
			'auction.deposit.csv',
			'auction.dates.csv', 
			'auction.bid.csv',
			'auction.bid_line.csv',
			'res.partner.address.csv'],
			'name': 'Auction Data', 
			'author': 'Tiny',
			'depends': ['base', 'auction'],
			'version': '1.0',
			'active': False,
			'demo_xml': [],
			'installable': True}
