#!/bin/sh

### BEGIN INIT INFO
# Provides:		etiny-server
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Enterprise Resource Management software
# Description:		Tiny ERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/tinyerp/etiny-server
NAME=etiny-server
DESC=etiny-server

test -x $DAEMON || exit 0

# Include tinyerp-server defaults
#. /opt/tinyerp/eTiny/etc/default/etiny-server

set -e

case "$1" in
	start)
		echo -n "Starting $DESC: "

		start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
			--chuid $USER --background --make-pidfile \
			--exec $DAEMON -- $DAEMON_OPTS

		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "

		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
			--oknodo

		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "

		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
			--oknodo

		sleep 1

		start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
			--chuid $USER --background --make-pidfile \
			--exec $DAEMON -- $DAEMON_OPTS

		echo "$NAME."
		;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
