# -*- encoding: utf-8 -*-
{
    "name":"Profile Chamber of Commerce",
    "version":"1.0",
    "author":"Tiny",
    "category":"Profile",
    "depends":[
        "project_retro_planning",
        "purchase_tender",
        "base_module_record",
        "base_report_creator",
        "account_analytic_package",
        "sale_expected_invoice_date",
        "account_payment",
        "l10n_be",
        "account_asset",
        "account_budget",
        "account_l10nbe_domiciliation",
        "hr_holidays",
        "cci_base_contact",
        "cci_partner",
        "cci_crm_profile",
        "cci_membership",
        "cci_event",
        "cci_mission",
        "cci_account",
        "cci_sales",
        "cci_purchase",
        "cci_translation",
        "cci_crm",
        "cci_timesheet",
    ],
    "demo_xml":[],
    "update_xml":[],
    "active":False,
    "installable":True,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:

