{
    "name":"cci profile",
    "version":"1.0",
    "author":"Tiny",
    "category":"Profile",
    "depends":[
        "base_contact",
        "cci_partner",
        "cci_base_contact",
        "event",
        "cci_event",
        "cci_crm_profile",
        "account_payment",
        "membership"
    ],
    "demo_xml":[],
    "update_xml":[],
    "active":False,
    "installable":True,
}
