#!/bin/sh

DOC_BUILD_DIR=${DOC_BUILD_DIR:-$(realpath $(dirname $0)/../odoo/openupgrade/doc)}
BASE_URL=https://github.com/OCA/OpenUpgrade/raw/
DOC_PARTS="7.0/openerp/openupgrade/doc/source/modules50-60.rst
7.0/openerp/openupgrade/doc/source/modules60-61.rst
7.0/openerp/openupgrade/doc/source/modules61-70.rst
8.0/openerp/openupgrade/doc/source/modules70-80.rst
9.0/openerp/openupgrade/doc/source/modules80-90.rst"
OUTPUT_DIR=${OUTPUT_DIR:-$DOC_BUILD_DIR}/build/html
OPENUPGRADELIB=https://github.com/OCA/OpenUpgradelib.git

for line in $DOC_PARTS; do
    name=$(basename $line)
    wget -q $BASE_URL/$line -O $DOC_BUILD_DIR/source/$name
done
OPENUPGRADE_PYTHON_PATH=$DOC_BUILD_DIR/../../../
if [ ! -d $DOC_BUILD_DIR/openupgradelib ]; then
    git clone --single-branch --depth=1 $OPENUPGRADELIB $DOC_BUILD_DIR/openupgradelib
else
    git -C $DOC_BUILD_DIR/openupgradelib pull --quiet
fi
export PYTHONPATH=$PYTHONPATH:$OPENUPGRADE_PYTHON_PATH:$DOC_BUILD_DIR/openupgradelib
mkdir -p $DOC_BUILD_DIR/source/.static
sphinx-build -q -d $DOC_BUILD_DIR/.doctrees -D latex_paper_size=a4 $DOC_BUILD_DIR/source $OUTPUT_DIR
