{
	"name" : "Personal Base",
	"version" : "1.1",
	"author" : "Sandas",
	"website" : "www.sandas.eu",
	"category" : "Sandas/Personal",
	"depends" : ["base","account"],
	"init_xml" : [],
	"demo_xml": [],
	"update_xml" : ['account_view.xml',
				    'account_wizard.xml',
				    'user_view.xml', 
				    'action_view.xml',
				    'security/ir.model.access.csv',
				    ],
	"description": "Sandas Personal Financials base module.",
	"installable" : True,
	"active" : False,
}
