name: Generate analysis files - cron and push

on:
  push:
    # when module merges are added to apriori, this
    # might cause changes in the analysis
    paths: ["openupgrade_scripts/apriori.py"]
  schedule:
    # every monday at 04:00
    - cron: "0 4 * * 1"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: choice
        options:
        - all
        - 18.0
        - 19.0

jobs:
  generate-analysis18:
    name: Generate analysis 18.0
    if: |
      github.repository == 'OCA/OpenUpgrade' && (github.event_name == 'schedule' || github.ref_name == '18.0') ||
      github.event_name == 'workflow_dispatch' && (inputs.version == '18.0' || inputs.version == 'all')
    uses: ./.github/workflows/generate-analysis.yml
    with:
      from_version: "17.0"
      to_version: "18.0"
  generate-analysis19:
    name: Generate analysis 19.0
    if: |
      github.repository == 'OCA/OpenUpgrade' && (github.event_name == 'schedule' || github.ref_name == '19.0') ||
      github.event_name == 'workflow_dispatch' && (inputs.version == '19.0' || inputs.version == 'all')
    uses: ./.github/workflows/generate-analysis.yml
    with:
      from_version: "18.0"
      to_version: "19.0"
