name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          # The pylint-odoo version we use here does not support python 3.10
          # https://github.com/OCA/oca-addons-repo-template/issues/80
          python-version: "3.9"
      - uses: pre-commit/action@v2.0.0
