[project]
name = "odoo-addons-oca-OpenUpgrade"
version = "19.0.20251225.0"
dependencies = [
    "odoo-addon-openupgrade_framework==19.0.*",
    "odoo-addon-openupgrade_scripts==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
